// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOWVnmcoAn-Jhklw89B4Cqe6g-H972dR4',
    appId: '1:970517225625:web:7de2039f7d8311286b1808',
    messagingSenderId: '970517225625',
    projectId: 'flutter-production-app-87af0',
    authDomain: 'flutter-production-app-87af0.firebaseapp.com',
    storageBucket: 'flutter-production-app-87af0.appspot.com',
    measurementId: 'G-9QGXR3BD8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcneKKSvgOOxNC4VlsEWZmLiE5yhqyb4s',
    appId: '1:970517225625:android:91ac350e3c2bcab76b1808',
    messagingSenderId: '970517225625',
    projectId: 'flutter-production-app-87af0',
    storageBucket: 'flutter-production-app-87af0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrIqHwP-K9OVH3XaKmSaPNj26nFt-cB1Y',
    appId: '1:970517225625:ios:4ef9698fe82a4c826b1808',
    messagingSenderId: '970517225625',
    projectId: 'flutter-production-app-87af0',
    storageBucket: 'flutter-production-app-87af0.appspot.com',
    iosClientId: '970517225625-91bafs6857a373scjtgmn17dup8l2u1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProductionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrIqHwP-K9OVH3XaKmSaPNj26nFt-cB1Y',
    appId: '1:970517225625:ios:4ef9698fe82a4c826b1808',
    messagingSenderId: '970517225625',
    projectId: 'flutter-production-app-87af0',
    storageBucket: 'flutter-production-app-87af0.appspot.com',
    iosClientId: '970517225625-91bafs6857a373scjtgmn17dup8l2u1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProductionApp',
  );
}
